botlabs-gg/yagpdb-docs-v2

.github/workflows/deploy.yml, README.md, content/_index.md, hugo.toml, layouts/partials/logo.html
Parts of the build (mainly images) were broken when testing on localhost.
This is because of baseURL weirdness; see the added comments in hugo.toml and deploy.yml.
Add a new page `getting-started.md`; it is not yet finished.
=> content;build: fix local build imgs, add new page

.github/workflows/deploy.yml
Fix hugo_cache not being where we expect it to be by setting the
HUGO_CACHEDIR env variable to something predetermined.
Improve the feedback on PRs by now also running on pull requests, but
then only build the website to catch some errors; do not set up GH Pages
nor upload any pages artifact.
Future work may entail adding some linters and grammar checkers.
=> ci: fix cache, improve feedback and build times

.github/workflows/deploy.yml, README.md
Vendor hugo modules into `_vendor/` before building the page in release
mode (i.e. with `hugo`).
Reportedly, hugo tends to fail with odd errors along the lines of
"Permission denied" when trying to build the site, due to some weird
file permissions on the (elsewhere) vendored module files.
Testing has concluded that running `hugo mod vendor` before building the
page fixes this issue as far as I can tell. Adjust the build
instructions in the README.md file to reflect this oddity.
Closes botlabs-gg/yagpdb-docs-v2#6 ("Fix Hugo Builds For Good").
=> hugo: vendor modules before building page

layouts/partials/menu-footer.html
Fix the unintentional underlining of other links in the menu sidebar by
assigning the `p` elements in the menu-footer partial a special class,
which we then specifically select for.
=> partials: fix weird underline in menu sidebar

.github/workflows/hugo.yml
Rename the workflow from deploy.yml to hugo.yml to be more descriptive
of what it is actually doing, given that it only really deploys when a
commit is pushed to the master (i.e. production) branch.
While we're at it, also fix a small typo messing up the HUGO_BASE_URL,
it should be botlabs-gg, not botlabs.gg.
=> workflows: rename deploy.yml to hugo.yml

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
This is a combination of two commits:
* meta: add contributing guidelines
Add contributing guidelines, outlining where to go for general support
and bug reports, as well as how to submit a pull request.
We define a specification for commit messages, such that it is easier to
read and parse the git shortlog and thus generate proper changelogs.
This specification is intended to present a basic "skill-check" to avoid
rushed contributions with no real value, but they are by no means meant
to be difficult to work with.
To make sure as many potential contributors as possible find these
guidelines, do link to it from the README, although GitHub should
already prompt contributors to read them, given it is located in any of
the documented locations where GitHub detects this special file.
* meta: …
=> meta: contrib guide and pr template

content/_index.md, content/getting-started.md
Refine the first two pages, mentioning the option to also contribute to
the documentation, and how the docs are intended to be structured.
Given how the docs repo is fairly hidden from public view (at least on
the support server), it is certainly worth mentioning *where* it is to
increase the chances of outside contributors seeing it.
The small note how we intend to structure the documentation serves the
simple and benign purpose of improving the reader's flow, even though
the menu sidebar should already do most of that.
**Terms**
=> docs/main: refine first two pages

hugo.toml
Tell Hugo to generate a dedicated search-page, improving UX when using
the included search-bar.
Currently, it just does nothing; that way, users will be redirected to
said dedicated page, listing all more or less matching results.
**Terms**
=> hugo: generate dedicated search-page

hugo.toml, layouts/partials/custom-header.html, static/css/menu.css
This CL is a combination of three commits. Due to the nature of this
branch ("general housekeeping"), I'll be merging this via a merge commit
rather than our usual squash-merge strategy, as the commits are
logically disjoint and don't really make sense to be squashed together.
* hugo: increase ToC endLevel to 4
Increase the markup.tableOfContents endLevel config to 4, so that some
relatively deeply nested headers still show up in the individual page's
ToC.
This may be especially important for future pages such as template
references, where we'll be using those higher-level headers fairly
extensively.
* hugo: remove some useless/ugly themes
Remove most of the themes that have no use beyond changing a single
colour around, or are just not very …
=> General Housekeeping / Formatting Tasks

content/core/_index.md, content/core/command-settings.md, content/core/control-panel-access.md, content/core/control-panel-logs.md
Assorted changes to the core section in the spirit of the PR title. Review commit-by-commit (some rationale is provided for the more extensive changes); please do not squash.
**Terms**
=> core: rewrite and elaborate for improved brevity & clarity

content/custom-commands/_index.md, content/custom-commands/commands.md
Similar to #23, but for the custom command category. These are largely very minor, albeit uncontroversial, nits and there are some diffs that are just my editor reflowing text (though I've tried to keep that to a minimum) -- sorry for the noise!
That said, I do have some more substantive feedback pertaining to these pages as a whole which are perhaps more interesting. In particular, I am wondering whether their current length is warranted; I worry that excessively long documentation may turn off users and hinder skimming. Compare, for instance, the custom command interface page with [its equivalent on the learn.yagpdb.xyz Gitbook](https://learn.yagpdb.xyz/the-custom-command-interface). The latter is considerably more succinct for two main reasons:
1. **Better spacing and formatting …
=> cc: reword and rewrite as needed for improved brevity & clarity

.github/workflows/hugo.yml
Update the workflow actions used in hugo.yml.
GitHub Actions emits some warnings regarding Node 16 deprecation and
recommends updating the workflows to the latest version running on Node
20.
**Terms**
=> workflows: update workflow actions

.vscode/markdown.code-snippets, content/docs/core/command-settings.md, content/docs/custom-commands/commands.md, content/docs/fun/soundboard.md, content/docs/moderation/advanced-automoderator/conditions.md, content/docs/moderation/logging.md, content/docs/moderation/moderation-overview.md, content/docs/moderation/verification.md, content/docs/notifications/general.md, content/docs/notifications/reddit.md, content/docs/notifications/streaming.md, content/docs/notifications/youtube.md, content/docs/reference/custom-command-examples.md, content/docs/reference/custom-embeds.md, content/docs/reference/custom-interactions.md, content/docs/reference/templates/functions.md, content/docs/reference/templates/template-scripting.md, content/docs/tools-and-utilities/autorole.md, content/docs/tools-and-utilities/self-assignable-roles.md, content/docs/welcome/getting-started.md, content/docs/welcome/premium.md
Standardize all callouts' contexts, titles, and icons using the
workspace snippets as a guide.
- Callouts previously using the "note" context now use the note
snippet.
- Caution callouts previously using the octagon icon now use the
danger snippet.
**Terms**
=> callouts: standardize callouts

assets/scss/common/_custom.scss, config/_default/markup.toml, layouts/_default/_markup/render-codeblock.html, package-lock.json, package.json, scripts/highlight.mjs
* Syntax highlighting in codeblocks don't look as good as they could (compare to current GitBook docs)
* At some point, we would like to switch a highlighting style specialized to custom commands instead of using Go, but currently Hugo provides no facility to do so: https://github.com/gohugoio/hugo/issues/11496
* Alternatives: switch away from Chroma (Hugo's default highlighter) to a different syntax highlighter
* However, most syntax highlighting libraries (notably, hljs and prism) render on client-side; Chroma runs at build time so the highlighted content is shipped directly to users
* Can we do better?
* (This PR) experiments with a different build-time highlighter: https://shiki.style/
* Shiki has additional benefits compared to all options above; see its website; it is also the …
=> all: highlight with shiki in production

content/docs/reference/templates/functions.md
This part of the docs currently has a typo where the codeblock ends for a bit and then starts again
(https://discord.com/channels/166207328570441728/384011387132706816/1276312920485003305)
**Terms**
=> Fix typo in functions doc

content/docs/reference/templates/functions.md
This PR tracks the progress of migrating the layout of the functions
reference from a table-based layout to a header-based layout.
I've pushed a preliminary commit showcasing how I imagine the layout
going forward and am looking for feedback on the proposal.
~~As I continue working on this, I will amend this commit and subsequently
force-push this branch.~~
I will push fixups as I go and then rebase + squash before merging.
**Terms**
=> docs: migrate functions reference layout to headers

.github/CONTRIBUTING.md
With this PR I hope to address some concerns voiced about the
contributing guide in `#documentation` et al. The guidelines were quite
confusingly written and did not provide a clear path for new
contributors, which may or may not have added to the sentiment towards
this guide.
I have now restructured the guide to be more linear and clearer about
the *why* of certain things. Below reproduced the commit message.
<details>
<summary>meta: refine contributing guide</summary>
The contributing guide was partly outdated, mentioning to run Hugo for
building / previewing the site and was generally confusingly written,
exhibiting a non-linear style.
Update it such that it can now be read linearly, outlining the new
preview / build process, explaining the markdown features we want
contributors to …
=> meta: refine contribution guide

config/_default/hugo.toml, config/_default/module.toml, config/_default/params.toml, config/postcss.config.js, package-lock.json, package.json
Migrate from Hyas to Thulite following the [Upgrade to Doks v1](https://getdoks.org/upgrade-guides/upgrade-to-v1/) guide
See also https://github.com/orgs/thuliteio/discussions/495#discussioncomment-11018673
**Terms**
=> Migrate from Hyas to Thulite

content/docs/reference/templates/functions.md
`closeThread` does not archive a thread if the lock flag is provided. It will do one or the other. Also adds a hint for
users who'd like to do both that they should lock before closing.
**Terms**
Signed-off-by: SoggySaussages <vmdmaharaj@gmail.com>
=> reference: improve accuracy of closeThread desc

content/docs/reference/templates/functions.md, content/learn/beginner/command-arguments.md
Correct the format the `min` and `max` values for a `duration` type `carg` accept.
**Terms**
=> reference/functions: correct carg duration min max

content/docs/reference/templates/functions.md
added information and examples about the new ability of sending complex messages with stickers.
This change should be merged because I painstakingly researched and wrote out the text to make it easy to read.
**Terms**
- [ X] I have read and understood this project's [Contributing Guidelines](CONTRIBUTING.md)
Signed-off-by: savage4618 <randomdad@randomdad.xyz>
=> Added sticker info to complexMessage function

content/docs/reference/templates/functions.md
I added message forward information to the complexMessage function based on information from the commit: https://github.com/botlabs-gg/yagpdb/pull/1764 
**Terms**
Signed off by: savage4618 <randomdad@randomdad.xyz>
=> added forwards to the complexMessage Section

content/docs/reference/templates/functions.md
> Spaces are always added between operands and a newline is appended.
`println` *always* inserts spaces within arguments, as defined in the
godoc: https://pkg.go.dev/fmt#Sprintln
Signed-off-by: Galen CC <galen8183@gmail.com>
**Terms**
=> tmpl: correct println description

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/lint.yml, .mdlrc, README.md, config/markdownlint.rb, content/discord.md, content/docs/core/command-settings.md, content/docs/custom-commands/commands.md, content/docs/fun/soundboard.md, content/docs/moderation/advanced-automoderator/triggers.md, content/docs/moderation/moderation-tools.md, content/docs/notifications/streaming.md, content/docs/notifications/youtube.md, content/docs/reference/custom-command-examples.md, content/docs/reference/custom-commands-limits.md, content/docs/reference/custom-interactions.md, content/docs/reference/how-to-get-ids.md, content/docs/reference/regex.md, content/docs/reference/templates/functions.md, content/docs/reference/templates/syntax-and-data.md, content/docs/tools-and-utilities/autorole.md, content/docs/tools-and-utilities/self-assignable-roles.md, content/docs/welcome/premium.md, content/learn/beginner/conditional-branching.md, content/learn/beginner/variables-and-data-types.md
Add and configure a markdown linter. While we're at it, also fix the
lints it threw, excluding select files (especially all-commands).
----
This is a combination of two commits. Review should not be required,
though it may be useful to review at least the first commit.
- **workflows: add and configure a Markdown linter**
- **all: lint markdown files**
**Terms**
=> all: lint markdown files

assets/js/custom.js, assets/scss/common/_custom.scss, config/postcss.config.js, content/docs/moderation/logging.md, content/docs/moderation/verification.md, content/docs/welcome/premium.md, layouts/partials/header/header.html, layouts/shortcodes/selfhosting.html
Implement a "selfhosting view" that optionally shows information only
relevant to or available on a selfhosted instance of YAGPDB.
Closes #25 -- see there for additional discussion.
**Terms**
=> frontend: add selfhosting view toggle

content/docs/custom-commands/commands.md
Luca pointed out a typo in the discord support server, and I wanted to PR something this morning, so this PR fixes that one specific typo, without regard to any other typos that may or may not be in the project.
Signed off by savage4618
**Terms**
- [x ] I have read and understood this project's [Contributing Guidelines](CONTRIBUTING.md)
=> Fix a single typo

content/docs/reference/templates/functions.md
This PR adds to the description of the `in` and `inFold` functions of custom command reference to specify the first argument of the functions can be a slice or string.
This PR also reorders the mentioned functions so that `inFold` follows `in`, which both allows `inFold`'s description to base off of `in`'s description and follows the order as seen with the `reFind` family of functions.
**Terms**
=> Reference: in(Fold) Description and Reorder

content/docs/reference/templates/functions.md
`sort` & `printf` are/were missing the actual function within the syntax display in the functions section.
Had a look through everything else and I am pretty sure it was just those that were missed
**Terms**
=> docs(functions): Missing sort and printf functions

.github/workflows/lint.yml, .mdlrc, config/.markdownlint.yaml, content/docs/reference/custom-commands-limits.md, content/docs/reference/custom-interactions.md, content/docs/reference/templates/functions.md
The currently used action to lint markdown files does not properly
produce annotations, which would be really useful to have. Use a newer
version that does support annotating files.
**Terms**
=> workflows: use new and maintained mdl implementation

content/docs/reference/templates/functions.md
Link to the template ticket type table in the createTicket function description
Recommendations on wording are very welcome
Signed-off-by: Galen CC <galen8183@gmail.com>
**Terms**
=> templates: link to template ticket type in createTicket description

content/docs/reference/custom-commands-limits.md
This PR fixes bold formatting and rewords the description in the reference > CC limits section for `deleteMessageReaction`
**Terms**
=> CC reference: limits: fix formatting and wording

content/docs/reference/templates/syntax-and-data.md
Signed-off-by: Galen CC <galen8183@gmail.com>
**Terms**
=> docs/reference: reword time syntax and data explanation

content/docs/reference/custom-interactions.md, content/docs/tools-and-utilities/self-assignable-roles.md
Reduce the callouts density to something more bearable and less yellow
and blue; especially some notes are better off incorporated into the
main text.
Closes #77
**Terms**
=> rolemenus: reduce callouts density, correct some grammar

content/docs/reference/templates/syntax-and-data.md, package-lock.json, package.json
Add markdownlint-cli2 (the one we're using in CI as well) as a dev
dependency, so that contributors can run the linter locally and don't
get stuck in review hell on GitHub.
While we're here, fix a link that the linter complained about.
- deps: add markdownlint-cli2 as devDependency
- reference: get rid of context-less "here" crosslink
**Terms**
=> deps: add markdownlint-cli2 as devDependency

content/docs/reference/custom-commands-limits.md, content/docs/reference/templates/functions.md
Adding in a known but currently undocumented limitation on execCC. The old docs elaborated on this a bit more, but I felt this was sufficient for the time.
**Terms**
=> added per channel per minute note

content/docs/reference/templates/functions.md
See botlabs-gg/yagpdb#1952 
**Terms**
=> functions: document is_components_v2 complexMessage flag
